version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk_network

  kibana:
    image: kibana:8.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  logstash:
    image: logstash:8.16.1
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk_network
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline

networks:
  elk_network:
    driver: bridge
