spring:
  application:
    name: T-Bank2024.Fintech-Java-dev-Spring
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:KudaGoLocalDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true

kudago:
  api:
    base:
      url: https://kudago.com/public-api/v1.4
    categories:
      url: /place-categories/
    locations:
      url: /locations/
    events:
      url: /events/
  limits:
    events:
      page_size: 100
      max_page: 10
# https://kudago.com/public-api/v1.4/events/?page=6&page_size=100&fields=title,dates,price,is_free,location
app:
  init:
    fixed-thread-pool-size: 2
    schedule-duration: PT1H


jwt:
  secret: mysuperSecretPasswordformysuperbestAppwithsuperloginandBisness123Good2wow3magic1
  short: 10m # 10 minutes
  long: 30d # 30 days

