spring:
  application:
    name: T-Bank2024.Fintech-Java-dev-Spring
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:KudaGoLocalDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: prod

kudago:
  api:
    base:
      url: https://kudago.com/public-api/v1.4
    categories:
      url: /place-categories/
    locations:
      url: /locations/

app:
  init:
    fixed-thread-pool-size: 2
    schedule-duration: PT1H
