version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk_network

  kibana:
    image: kibana:8.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  logstash:
    image: logstash:8.16.1
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

    ports:
      - "9600:9600"
    networks:
      - elk_network
    volumes:
      - ../logback:/usr/share/logstash/data
      - ../logging/logstash/config/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../logging/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../logs:/usr/share/logstash/logs

networks:
  elk_network:
    driver: bridge
